### ISSUE TITLE
Foohid problem and solution

### ISSUE THREAD

**Issue by ysoldak** [garyjohnson/opentx-ble-joystick#3]
First of all, thanks for the great app that enabled me to use my new X7S as a wireless controller on my Mac. USB slot is so unfortunately located on these radios so it is a blessing indeed to be able and skip the wire!

Now, the problem. Foohid is not available to download anymore, development was halted and dmg file removed.
Fear not, there is a solution!
Download and install "Desktop" version of VIKEY app from https://vikey.20tab.com it brings foohid with it. You may need to reboot your Mac.

Works for me with stock OpenTX 2.2.2 on Taranis Q X7S and macOS Mojave (10.14.2) on MacBook Pro.

Would it be a good idea to embed foohid (or alike) into opentx-ble-joystick app?

**Comment by garyjohnson** [comment]
Thanks -- rather than install vikey I've attached a [known-original copy of Foohid 0.2.1](
https://github.com/garyjohnson/opentx-ble-joystick/releases/download/1.3/foohid-0.2.1.dmg) to the [last release](https://github.com/garyjohnson/opentx-ble-joystick/releases/tag/1.3). I'm not sure why the original author took them down, but they did post a cryptic message about thread-safety and security, so **use at your own risk**.
